### ISSUE TITLE
Failing to install google-cloud-run via PyPI on Cloud Composer

### ISSUE THREAD

**Issue by crisol3036** [googleapis/python-run#98]
#### Environment details

  - OS type and version: Google Cloud Composer, tried with versions `1.20.11`, `2.1.14` and `2.1.15`
  - Airflow version: tried with `2.4.3` and `2.5.1`
  - Python version: `3.8.12` as per the [Composer doc](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images)
  - pip version: `20.2.4` as per the [Composer doc](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images)
  - `google-cloud-run` version: I've tried with `0.7.1`, `0.7.0`, `0.6.0` and `0.5.0`

#### Steps to reproduce

  1. Create a Composer, either version 1 or 2. With any version of Airflow
  2. In that Composer environment, go to the *PyPI packages* tab and click *Edit*
  3. Add the package `google-cloud-run`. Either without specifying a version or specifying any of the latest: `0.7.1`, `0.7.0`, `0.6.0` or `0.5.0`
  4. Click *Save* and wait while it updates

#### Direct stack trace displayed on Composer

```
Failed to install PyPI packages. mysql-connector-python 8.0.32 has requirement protobuf<=3.20.3,>=3.11.0, but you have protobuf 4.23.0.
```

I tried:

- Changing the `protobuf` version to accommodate for the `mysql-connector-python` requirements (so, setting `protobuf<=3.20.3,>=3.11.0`)
- But then it threw another error for another conflict with another package
- And so I re-accommodated the package versions again. And  another conflict again
- And then at one point I was blocked because two different packages required different versions of the same package

How can I effectively install `google-cloud-run` on Composer?

I don't know which dependency of `google-cloud-run` is the one that's conflicting with at least one of the packages that are installed by default on Composer ([these](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images)).

Do you know if it'll be long until `google-cloud-run` is installed by default on Composer? Like so many of the Google Cloud APIs are.

**Comment by parthea** [comment]
`composer-2.3.0-airflow-2.5.1` now allows protobuf >= 4. Please use the latest version of composer. I'm going to close this issue as resolved but please feel free to open a new issue if required.

https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images

**Comment by crisol3036** [comment]
It works, thanks @parthea 🥳
